import { utils } from './utils';
import { Component, IFuture } from './component';

/** 
 * Enumeration of possible data types for fields 
 */
export enum DataType
{
    Unknown,
    String,
    Integer,
    Double,
    Date,
    DateTime,
    Boolean,
    Blob
}

/**
 *  IField - holds meta information about fields
 */
export interface IField
{
    fieldName: string;
    dataType: DataType;
    dataSize?: number;
    format?: string;
    required?: boolean;
}

export interface IObject
{
    [index: string]: any;
}

/**
 * IRecord - describes a plain record of data. Record is required to know its record set
 */
export interface IRecord extends IObject
{
    recordSet: IRecordSet;
    old?: IObject;
}

/**
 * IActive descrbies an object that could have an active state
 */
export interface IActive
{
    active: boolean;
}

/**
 * ICredentials describes an object that contains credentials info
 */
export interface ICredentials
{
    userName: string;
    password: string;
}

/**
 * IConnectionParams describes an object that contains connection params, including credentials
 */
export interface IConnectionParams extends ICredentials
{
    [index: string]: string;
}

/**
 * IRecordSet - describes a set of records with meta-data
 */
export interface IRecordSet
{
    fields: IField[];
    recordCount: number;
    getRecord(index: number): IRecord;
}

/**
 * IPartialSet - describes a record set that can be partially fetched
 */
export interface IPartialSet extends IRecordSet
{
    totalCount: number;
    fetch(count: number): IFuture;
}

/**
 * RecordState enum - the state of editable record
 */
export enum RecordState { Browse, Insert, Edit }

/**
 * IEditable - describes methods required to edit a record (CRUD) 
 */
export interface IEditable
{
    insert(append?: boolean): void;
    edit(): void;
    post(): void;
    cancel(): void;
    delete(): void;
    getState(): RecordState;
}

/**
 * IReference describes a reference to a current record (object)
 */
export interface IReference
{
    current: IRecord;
}

/**
 * Instance of IValueConverter can be attached to a data link to convert between the formats
 * of data source and data control.  
 */
export interface IValueConverter
{
    /** convert data from dataSource format to dataLink format */
    decode(sender: any, value: any): any;
    /** convert data from dataSource format to dataLink format */
    encode(sender: any, value: any): any;
}

/**
 * ICursor describes a navigation mechanism on a record set
 */
export interface ICursor extends IReference
{
    eof: boolean;
    next();
    prior();
    first();
    last();
    count: number;
    locate(values: any): boolean;
}

/**
 * IUpdatable describes an object that can lock updates
 */
export interface IUpdatable
{
    beginUpdate();
    endUpdate();
    isUpdating(): boolean;
}


/**
 * EventType - enumerates types of events generated by data source
 */
export enum EventType { StateChanged, DataChanged, CursorMoved, Refreshed };

/**
 * IDataSource describes an object that maintains data links 
 */
export interface IDataSource 
{
    addLink(link: IDataLink): void;
    removeLink(link: IDataLink): void;
    notifyLinks(eventType: EventType, data: any): void;
}

/**
 * IRecordSource provides access to a single record of data
 */
export interface IRecordSource extends IDataSource, IReference, IEditable
{

}

/**
 * IRecordSetSource - provides access to a record set 
 */
export interface IRecordSetSource extends IRecordSource, ICursor
{

}

/**
 * IDataLink - describes a data link located on the control's (data consumer) side
 */
export interface IDataLink
{
    onChange(eventType: EventType, data: any): void;
}

/**
 * IOnChangeEvent - event raised when something changes in the data source
 */
export interface IOnChangeEvent
{
    (eventType: EventType, data: any): void;
}

/**
 * SimpleDataLink - a generic implementation of a data link for single field controls
 */
export class SimpleDataLink implements IDataLink
{
    protected _dataSource: IRecordSource;
    dataField: string;

    constructor(public onChangeEvent: IOnChangeEvent, public converter?: IValueConverter) { }

    get dataSource(): IRecordSource { return this._dataSource; }
    set dataSource(value: IRecordSource)
    {
        if (this._dataSource != value)
        {
            if (this._dataSource)
                this._dataSource.removeLink(this);
            this._dataSource = value;
            if (this._dataSource)
                this._dataSource.addLink(this);
        }
    }
    onChange(eventType: EventType, data: any): void 
    {
        if (this.onChangeEvent)
            this.onChangeEvent(eventType, data);
    }
}

/**
 * FieldDataLink - a generic implementation of a data link for single field controls
 */
export class FieldDataLink extends SimpleDataLink
{
    get value(): any
    {
        let res = null;
        if (this.dataSource && this.dataSource.current && this.dataField != '')
        {
            res = this.dataSource.current[this.dataField];
            if (this.converter)
                res = this.converter.decode(this, res);
        }
        return res;
    }
    set value(val: any)
    {
        if (this.dataSource && this.dataSource.current && this.dataField != '')
        {
            if (this.dataSource.getState() == RecordState.Browse)
                this.dataSource.edit();
            if (this.converter)
                val = this.converter.decode(this, val);
            this.dataSource.current[this.dataField] = val;
            this.dataSource.notifyLinks(EventType.DataChanged, this.dataField);
        }
    }
}

/**
 * SimpleSource - generic implementation of a data source for objects
 */
export class SimpleSource implements IRecordSource
{
    protected _state: RecordState;
    protected _links: IDataLink[] = [];

    constructor(public current: IRecord)
    {
    }

    addLink(link: IDataLink): void
    {
        this._links.push(link);
    }
    removeLink(link: IDataLink): void
    {
        let num = this._links.indexOf(link);
        if (num >= 0)
            this._links.splice(num);
    }
    notifyLinks(eventType: EventType, data: any): void
    {
        /*
        for (let i = 0; i < this._links.length; i++)
            this._links[i].onChange(eventType, data);
            */
    }
    insert(append?: boolean): void
    {
        // throw 'insert is not supported';
    }
    edit(): void
    {
        this.current.old = null;
        this.current.old = utils.extend(this.current, {});
        this._state = RecordState.Edit;
    }
    post(): void
    {
        this._state = RecordState.Browse;
    }
    cancel(): void
    {
        this._state = RecordState.Browse;
    }
    delete(): void
    {
        throw 'delete is not supported';
    }
    getState(): RecordState
    {
        return this._state;
    }
}
