import { utils } from './utils';
import { Component, IFuture } from './component';

/** 
 * Enumeration of possible data types for fields 
 */
export enum DataType {
    Unknown,
    String,
    Integer,
    Double,
    Date,
    DateTime,
    Boolean,
    Blob
}

/**
 *  IField - holds meta information about fields
 */
export interface IField {
    fieldName: string;
    dataType: DataType;
    dataSize?: number;
    format?: string;
    required?: boolean;
}

/**
 * IExpression - generic expression function
 */
export interface IExpression {
    (value: IRecord): string;
}

/** 
 * IFields - defines a list of fields
 */
export interface IFields {
    fields: IField[];
}

/**
 * IRecord - defined a generic object as a prop->value map
 */
export interface IRecord {
    [index: string]: any;
}

/**
 * IActive descrbies an object that could have an active state
 */
export interface IActive {
    active: boolean;
}

/**
 * ICredentials describes an object that contains credentials info
 */
export interface ICredentials {
    userName: string;
    password: string;
}

/**
 * IConnectionParams describes an object that contains connection params, including credentials
 */
export interface IConnectionParams extends ICredentials {
    [index: string]: string;
}

/**
 * IRecordSet - describes a set of records with meta-data
 */
export interface IRecordSet extends IFields {
    recordCount: number;
    getRecord(index: number): IRecord;
}

/**
 * IPartialSet - describes a record set that can be partially fetched
 */
export interface IPartialSet extends IRecordSet {
    totalCount: number;
    fetch(count: number): IFuture;
}

/**
 * RecordState enum - the state of editable record
 */
export enum RecordState { Empty, Browse, Insert, Edit }

/**
 * IEditableRecord - describes methods required to edit a record (CRUD) 
 */
export interface IEditableRecord {
    edit(): void;
    post(): void;
    cancel(): void;
    getState(): RecordState;
    oldValue: IRecord;
}

/**
 * IEditableList - describes methods required to edit a list of records
 */
export interface IEditableList {
    insert(): void;
    delete(): void;
}

/**
 * IReference describes a reference to a current record (object)
 */
export interface IReference extends IFields {
    current: IRecord;
}

/**
 * Instance of IValueConverter can be attached to a data link to convert between the formats
 * of data source and data control.  
 */
export interface IValueConverter {
    /** convert data from dataSource format to dataLink format */
    decode(sender: any, value: any): any;
    /** convert data from dataSource format to dataLink format */
    encode(sender: any, value: any): any;
}

/**
 * ICursor describes a navigation mechanism on a record set
 */
export interface ICursor extends IReference {
    eof(): boolean;
    next();
    prior();
    first();
    last();
    recordCount(): number;
    getRecord(index: number): IRecord;
    locate(values: any): boolean;
    currentIndex: number;
    /** Array of records indexes used in cursor navigation */
    getFilteredRecords(): number[];
    setFilteredRecords(indexed: number[]);
}

/**
 * IUpdatable describes an object that can lock updates
 */
export interface IUpdatable {
    beginUpdate();
    endUpdate();
    isUpdating(): boolean;
}

/**
 * EventType - enumerates types of events generated by data source
 */
export enum EventType { StateChanged, DataChanged, CursorMoved, Refreshed };

/**
 * IDataSource describes an object that maintains data links 
 */
export interface IDataSource {
    addLink(link: IDataLink): void;
    removeLink(link: IDataLink): void;
    notifyLinks(eventType: EventType, data?: any): void;
}

/**
 * IRecordSource provides access to a single record of data
 */
export interface IRecordSource extends IDataSource, IReference, IEditableRecord {

}

/**
 * IRecordSetSource - provides access to a record set 
 */
export interface IRecordSetSource extends IRecordSource, ICursor, IEditableList {

}

/**
 * IDataLink - describes a data link located on the control's (data consumer) side
 */
export interface IDataLink {
    onChange(eventType: EventType, data: any): void;
}

/**
 * IOnChangeEvent - event raised when something changes in the data source
 */
export interface IOnChangeEvent {
    (eventType: EventType, data?: any): void;
}

/**
 * BaseDataLink - a generic implementation of a data link for single field controls
 */
export class BaseDataLink<T extends IRecordSource | IRecordSetSource> implements IDataLink {
    protected _dataSource: T;

    constructor(public onChangeEvent: IOnChangeEvent) { }

    protected setDataSource(value: T) {
        if (this._dataSource != value) {
            if (this._dataSource)
                this._dataSource.removeLink(this);
            this._dataSource = value;
            if (this._dataSource)
                this._dataSource.addLink(this);
            this.onChange(EventType.Refreshed);
        }
    }

    public get dataSource(): T { return this._dataSource; }
    public set dataSource(value: T) { this.setDataSource(value); }
    public onChange(eventType: EventType, data?: any): void {
        if (this.onChangeEvent)
            this.onChangeEvent(eventType, data);
    }
}

/**
 * FieldDataLink - a generic implementation of a data link for single field controls
 */
export class FieldDataLink extends BaseDataLink<IRecordSource> {
    protected _dataField: string;

    constructor(public onChangeEvent: IOnChangeEvent, public converter?: IValueConverter) {
        super(onChangeEvent);
    }
    public get dataField() { return this._dataField; }
    public set dataField(value: string) {
        if (this._dataField != value) {
            this._dataField = value;
            if (this.dataSource)
                this.onChange(EventType.Refreshed);
        }
    }
    public get value(): any {
        let res = null;
        if (this._dataSource && this._dataSource.current && this._dataField != '') {
            if (this._dataField == '*')
                res = utils.extend(this._dataSource.current, {});
            else
                res = this._dataSource.current[this._dataField];
            if (this.converter)
                res = this.converter.decode(this, res);
        }
        return res;
    }
    public set value(val: any) {
        if (this._dataSource && this._dataSource.current && this._dataField != '') {
            if (this._dataSource.getState() == RecordState.Browse)
                this._dataSource.edit();
            if (this.converter)
                val = this.converter.decode(this, val);
            if (this._dataField == '*')
                utils.assign(val, this._dataSource.current);
            else
                this._dataSource.current[this.dataField] = val;
            this._dataSource.notifyLinks(EventType.DataChanged, this._dataField);
        }
    }
}

/**
 * RecordSetDataLink - a generic implementation of data link for record sets (list or grid controls)
 */
export class RecordSetDataLink extends BaseDataLink<IRecordSetSource> {
}

/**
 * LookupDataLink - a generic implementation of a data link for lookup controls
 */
export class LookupDataLink extends RecordSetDataLink {
    protected _keyField: string;
    protected _displayField: string;
    protected _displayExpression: IExpression;

    public get keyField() { return this._keyField; }
    public set keyField(value: string) {
        if (this._keyField != value) {
            this._keyField = value;
            if (this.dataSource)
                this.onChange(EventType.Refreshed);
        }
    }
    public get displayField() { return this._displayField; }
    public set displayField(value: string) {
        if (this._displayField != value) {
            this._displayField = value;
            if (this.dataSource)
                this.onChange(EventType.Refreshed);
        }
    }
    public get displayExpression() { return this._displayExpression; }
    public set displayExpression(value: IExpression) {
        if (this._displayExpression != value) {
            this._displayExpression = value;
            if (this.dataSource)
                this.onChange(EventType.Refreshed);
        }
    }
    public getDisplayValue(record: IRecord): string {
        if (this._displayExpression)
            return this._displayExpression(record).toString();
        else {
            let fld = (this._displayField) ? this._displayField : this._keyField;
            return record[fld];
        }
    }
}

/**
 * getObjectFields(obj: any) - creates a list of geenric field definitions based on object structure
 */
export function getObjectFields(obj: any): IField[] {
    let res: IField[] = [];
    for (let id in obj)
        if (obj.hasOwnProperty(id))
            res.push({
                fieldName: id,
                dataType: DataType.String
            });
    return res;
}

/**
 * BaseSource - base data source implementation, handling data links
 */
export class BaseSource implements IDataSource {
    protected _links: IDataLink[] = [];

    public addLink(link: IDataLink): void {
        this._links.push(link);
    }
    public removeLink(link: IDataLink): void {
        let num = this._links.indexOf(link);
        if (num >= 0)
            this._links.splice(num);
    }
    public notifyLinks(eventType: EventType, data?: any): void {
        for (let i = 0; i < this._links.length; i++) {
            this._links[i].onChange(eventType, data);
        }
    }
}

/**
 * RecordSource - generic implementation of a data source for objects
 */
export class RecordSource extends BaseSource implements IRecordSource {
    protected _state: RecordState;
    protected _current: IRecord;
    protected _oldValue: IRecord = {};
    protected _fields: IField[] = [];

    protected setState(value: RecordState): void {
        if (this._state != value) {
            this._state = value;
            this.notifyLinks(EventType.StateChanged, value);
        }
    }

    public checkCurrent() {
        if (!this._current)
            utils.RaiseError('Record does not exist');
    }

    public get current(): IRecord { return this._current; }

    public set current(value: IRecord) {
        if (value != this._current) {
            if (this._current)
                this.cancel();
            this._current = value;
            this._fields = getObjectFields(value);
            this._state = (value) ? RecordState.Browse : RecordState.Empty;
            this.notifyLinks(EventType.Refreshed);
        }
    }

    public get oldValue(): IRecord {
        this.checkCurrent();
        return this._oldValue;
    }

    public get fields(): IField[] { return this._fields; }

    public edit(): void {
        this.checkCurrent();
        this._oldValue = {};
        utils.assign(this.current, this._oldValue);
        this.setState(RecordState.Edit);
    }
    public post(): void {
        this.checkCurrent();
        this.setState(RecordState.Browse);
    }
    public cancel(): void {
        this.checkCurrent();
        utils.assign(this._oldValue, this.current);
        this._oldValue = {};
        this.setState(RecordState.Browse);
    }
    public getState(): RecordState {
        return this._state;
    }
}

/**
 * RecordSetSource - implementation of record set source for an array of objects 
 */
export class RecordSetSource extends BaseSource implements IRecordSetSource, IUpdatable {
    protected _records: IRecord[] = [];
    protected _curIndex = -1;
    protected _state: RecordState;
    protected _oldValue: IRecord = {};
    protected _fields: IField[] = [];
    protected _updateCounter = 0;
    /** Array of records indexes used in cursor navigation */
    protected _filteredRecords: number[] = [];

    public notifyLinks(eventType: EventType, data?: any): void {
        if (this._updateCounter == 0)
            for (let i = 0; i < this._links.length; i++) {
                this._links[i].onChange(eventType, data);
            }
    }

    public beginUpdate(): void {
        this._updateCounter++;
    }

    public endUpdate(): void {
        this._updateCounter--;
        if (this._updateCounter == 0)
            this.notifyLinks(EventType.Refreshed);
    }

    public isUpdating(): boolean { return this._updateCounter != 0; }

    public get currentIndex(): number {
        this.checkList();
        return this._curIndex;
    }

    public set currentIndex(value) {
        this.checkList();
        if (value >= this._records.length)
            value = this._records.length - 1;
        if (value != this._curIndex) {
            this.post();
            this._curIndex = value;
            this.notifyLinks(EventType.CursorMoved);
        }
    }

    protected setState(value: RecordState): void {
        if (this._state != value) {
            this._state = value;
            this.notifyLinks(EventType.StateChanged, value);
        }
    }

    public get current(): IRecord {
        if (this._curIndex >= 0) {
            if (this._filteredRecords.length > 0)
                return this._records[this._filteredRecords[this._curIndex]];
            else
                return this._records[this._curIndex];
        }
        else
            return null;
        //return ((this._curIndex >= 0)) ? this._records[this._curIndex] : null;
    }

    public set records(value: IRecord[]) {
        if (value != this._records) {
            this.post();
            this._records = value;
            this._curIndex = (value && value.length > 0) ? 0 : -1;
            this.notifyLinks(EventType.Refreshed);
        }
    }
    public get oldValue(): IRecord { return this._oldValue; }

    public get fields(): IField[] { return this._fields; }

    public getState(): RecordState {
        return this._state;
    }
    public checkList(): void {
        if (!this._records)
            utils.RaiseError('List is not assigned');
    }
    public checkCurrent(): void {
        this.checkList();
        if (!this.current)
            utils.RaiseError('Record does not exist');
    }

    // Editable methods

    public edit(): void {
        if (this._state == RecordState.Browse) {
            this.checkCurrent();
            this._oldValue = {};
            utils.assign(this.current, this._oldValue);
            this.setState(RecordState.Edit);
        }
    }
    public post(): void {
        if (this._state && this._state != RecordState.Browse) {
            this.checkCurrent();
            this._oldValue = {};
            this.setState(RecordState.Browse);
        }
    }
    public cancel(): void {
        if (this._state && this._state != RecordState.Browse) {
            this.checkCurrent();
            utils.assign(this._oldValue, this.current);
            this._oldValue = {};
            this.setState(RecordState.Browse);
        }
    }
    public insert(): void {
        this.checkList();
        this.post();
        this._records.push({});
        this._curIndex = this._records.length - 1;
        this._oldValue = {};
        this.setState(RecordState.Insert);
    }
    public delete(): void {
        this.checkCurrent();
        this.cancel();
        this._records.splice(this._curIndex);
        if (this._curIndex >= this._records.length)
            this._curIndex = this._records.length - 1;
        this.notifyLinks(EventType.CursorMoved);
    }

    // Cursor methods
    public eof(): boolean {
        return this.currentIndex >= this._records.length;
    }
    public next(): void {
        if (!this.eof())
            this.currentIndex++;
    }
    public prior(): void {
        if (this.currentIndex > 0)
            this.currentIndex--;
    }
    public first(): void {
        this.currentIndex = 0;
    }
    public last(): void {
        this.currentIndex = this.recordCount() - 1;
    }
    public recordCount(): number {
        if (this._records && this._filteredRecords.length > 0)
            return this._filteredRecords.length;
        else
            return (this._records) ? this._records.length : 0;
    }
    public compareRecord(obj, values) {
        for (let id in obj) {
            if (obj.hasOwnProperty(id) && values.hasOwnProperty(id) && values[id] != obj)
                return false;
        }
        return true;
    }
    public locate(values: any): boolean {
        for (let i = 0; i < this.recordCount(); i++) {
            if (this.compareRecord(this._records[i], values)) {
                this.currentIndex = i;
                return true;
            }
        }
        return false;
    }
    public getRecord(index: number): IRecord {
        if (this._filteredRecords.length > 0)
            return this._records[this._filteredRecords[index]];
        else
            return this._records[index];
    }
    public getFilteredRecords(): number[] {
        return this._filteredRecords;
    }
    public setFilteredRecords(indexes: number[]) {
        this._filteredRecords = indexes;
        this._curIndex = 0;
        //this.notifyLinks(EventType.Refreshed);
    }

}